package app

import (
	"strings"
	"testing"
	"time"

	"github.com/bwagner5/triad/pkg/registry"

	"github.com/aws/lightsailctl/pkg/lightsail"
)

func TestResourceAppDetailView(t *testing.T) {
	res := Resource(nil, nil)
	if res.Detail == nil {
		t.Fatal("Resource Detail is nil")
	}

	now := time.Now()
	view := res.Detail(App{
		Name:   "api",
		Envs:   "dev",
		Region: "us-east-1",
		State:  "OK",
		Age:    "2026-04-01T12:00:00Z",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance:  "box-a",
				Status:    "healthy",
				Endpoints: []string{"http://203.0.113.10:8080"},
				LastDeploy: &lightsail.DeployInfo{
					Timestamp: now.Add(-5 * time.Minute),
				},
				Containers: []lightsail.ContainerStatus{
					{
						Name:      "current-web-1",
						Service:   "web",
						Status:    "running",
						StartedAt: now.Add(-5 * time.Minute),
						Endpoints: []string{"http://203.0.113.10:8080"},
					},
				},
			}},
		},
		envBuckets: map[string]string{"dev": "ls--123--api--dev"},
	})

	assertDetailRow(t, view, "Name", "api")
	assertDetailRow(t, view, "Region", "us-east-1")
	assertDetailRow(t, view, "Instance", "box-a")
	assertDetailRow(t, view, "Health", "● healthy")
	// Container row uses the compose service name, not the container
	// name, and lives under its own Services section.
	assertDetailRow(t, view, "  web", "● running  up 5m ago")
	// Endpoint is nested under the service (4-space indent).
	assertDetailRow(t, view, "    Endpoint", "http://203.0.113.10:8080")
	assertSectionTitle(t, view, "Services (dev)")
	assertSectionTitle(t, view, "Environment: dev")
}

func TestAppDetailViewShowsUsefulEmptyState(t *testing.T) {
	view := appDetail(App{Name: "api"})
	assertDetailRow(t, view, "Name", "api")
	assertDetailRow(t, view, "Status", "no environments yet — run deploy to create one")
}

func TestAppDetailViewFallsBackForUnknownItem(t *testing.T) {
	view := appDetail(struct{ Name string }{Name: "api"})
	if len(view.Sections) != 0 {
		t.Fatalf("unexpected detail view for unknown item: %+v", view)
	}
}

func TestAppDetailUnenrichedFallback(t *testing.T) {
	view := appDetail(App{
		Name:      "api",
		Envs:      "dev",
		Instances: "box-a",
		Endpoints: "http://1.2.3.4:8080",
		Status:    "dev: 1/1",
	})
	assertDetailRow(t, view, "Instances", "box-a")
	assertDetailRow(t, view, "Endpoints", "http://1.2.3.4:8080")
	assertDetailRow(t, view, "Health", "dev: 1/1")
}

func TestAppDetailDropsAutoGeneratedImage(t *testing.T) {
	// Compose-built image names like "current-web" have no tag or
	// registry path and duplicate the service name; the view should
	// hide them.
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Containers: []lightsail.ContainerStatus{
					{Name: "current-web-1", Service: "web", Image: "current-web", Status: "running"},
				},
			}},
		},
	})
	val := getRow(view, "  web")
	if val == "" {
		t.Fatal("expected service row for 'web'")
	}
	if strings.Contains(stripAnsi(val), "current-web") {
		t.Errorf("auto-generated image should be hidden; got %q", val)
	}
}

func TestAppDetailShowsRegistryImage(t *testing.T) {
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Containers: []lightsail.ContainerStatus{
					{Name: "current-db-1", Service: "db", Image: "postgres:16", Status: "running"},
				},
			}},
		},
	})
	val := stripAnsi(getRow(view, "  db"))
	if !strings.Contains(val, "postgres:16") {
		t.Errorf("registry image should be shown; got %q", val)
	}
}

func TestAppDetailMultipleServicesWithPerServiceEndpoints(t *testing.T) {
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Endpoints: []string{
					"http://1.2.3.4:8080",
					"http://1.2.3.4:8081",
				},
				Containers: []lightsail.ContainerStatus{
					{Name: "current-svc1-1", Service: "svc1", Status: "running", Endpoints: []string{"http://1.2.3.4:8080"}},
					{Name: "current-svc2-1", Service: "svc2", Status: "running", Endpoints: []string{"http://1.2.3.4:8081"}},
				},
			}},
		},
	})
	assertDetailRow(t, view, "  svc1", "● running")
	assertDetailRow(t, view, "  svc2", "● running")
	// Each endpoint appears exactly once, nested under its service.
	endpoints := collectRows(view, "    Endpoint")
	if len(endpoints) != 2 {
		t.Fatalf("expected 2 endpoint rows; got %d: %v", len(endpoints), endpoints)
	}
	if !contains(endpoints, "http://1.2.3.4:8080") || !contains(endpoints, "http://1.2.3.4:8081") {
		t.Errorf("endpoints missing or wrong: %v", endpoints)
	}
}

func TestStatusBadgeColors(t *testing.T) {
	cases := []struct {
		status string
		symbol string
	}{
		{"healthy", "●"},
		{"running", "●"},
		{"degraded", "◐"},
		{"starting", "◐"},
		{"idle", "◐"},
		{"down", "○"},
		{"unhealthy", "○"},
		{"exited", "○"},
	}
	for _, tc := range cases {
		got := stripAnsi(statusBadge(tc.status))
		want := tc.symbol + " " + tc.status
		if got != want {
			t.Errorf("statusBadge(%q) = %q, want %q", tc.status, got, want)
		}
		// Raw output must include ANSI escapes (otherwise we'd know
		// colorization is silently disabled).
		if raw := statusBadge(tc.status); raw == got {
			t.Errorf("statusBadge(%q) is unstyled: %q", tc.status, raw)
		}
	}
}

func TestStatusBadgeUnknownFallsBack(t *testing.T) {
	got := statusBadge("some-weird-state")
	if got != "some-weird-state" {
		t.Errorf("unknown status should pass through unchanged; got %q", got)
	}
	if statusBadge("") != "unknown" {
		t.Errorf("empty status should render 'unknown'")
	}
}

func TestShowImage(t *testing.T) {
	cases := []struct {
		img  string
		want bool
	}{
		{"", false},
		{"current-web", false},  // auto-generated
		{"myapp-backend", false}, // auto-generated
		{"nginx:latest", true},  // tagged
		{"ghcr.io/owner/app", true}, // registry path
		{"docker.io/library/redis:7", true},
	}
	for _, tc := range cases {
		c := lightsail.ContainerStatus{Image: tc.img}
		if got := showImage(c); got != tc.want {
			t.Errorf("showImage(%q) = %v, want %v", tc.img, got, tc.want)
		}
	}
}

// --- helpers ---

func assertDetailRow(t *testing.T, view registry.DetailView, label, want string) {
	t.Helper()
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				if got := stripAnsi(row.Value); got != want {
					t.Fatalf("%s = %q; want %q", label, got, want)
				}
				return
			}
		}
	}
	t.Fatalf("detail row %q not found in %+v", label, view)
}

func assertSectionTitle(t *testing.T, view registry.DetailView, title string) {
	t.Helper()
	for _, section := range view.Sections {
		if section.Title == title {
			return
		}
	}
	t.Fatalf("section %q not found in %+v", title, view)
}

func getRow(view registry.DetailView, label string) string {
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				return row.Value
			}
		}
	}
	return ""
}

func collectRows(view registry.DetailView, label string) []string {
	var out []string
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				out = append(out, stripAnsi(row.Value))
			}
		}
	}
	return out
}

func contains(s []string, want string) bool {
	for _, v := range s {
		if v == want {
			return true
		}
	}
	return false
}

// stripAnsi removes CSI-SGR escape sequences so test assertions can
// match plain text regardless of whether lipgloss colorized the value.
// Mirrors the helper used in triad's tui tests.
func stripAnsi(s string) string {
	var b strings.Builder
	in := false
	for _, r := range s {
		if r == 0x1b {
			in = true
			continue
		}
		if in {
			if r == 'm' {
				in = false
			}
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}
