// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package app

import (
	"strings"
	"testing"
	"time"

	"github.com/bwagner5/triad/pkg/registry"

	"github.com/aws/lightsailctl/pkg/lightsail"
)

func TestResourceAppDetailView(t *testing.T) {
	res := Resource(nil, nil)
	if res.Detail == nil {
		t.Fatal("Resource Detail is nil")
	}

	now := time.Now()
	view := res.Detail(App{
		Name:   "api",
		Envs:   "dev",
		Region: "us-east-1",
		State:  "OK",
		Age:    "2026-04-01T12:00:00Z",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance:  "box-a",
				Status:    "healthy",
				Endpoints: []string{"http://203.0.113.10:8080"},
				LastDeploy: &lightsail.DeployInfo{
					Timestamp: now.Add(-5 * time.Minute),
				},
				Containers: []lightsail.ContainerStatus{
					{
						Name:      "current-web-1",
						Service:   "web",
						Status:    "running",
						StartedAt: now.Add(-5 * time.Minute),
						Endpoints: []string{"http://203.0.113.10:8080"},
					},
				},
			}},
		},
		envBuckets: map[string]string{"dev": "ls--123--api--dev"},
	})

	assertDetailRow(t, view, "Name", "api")
	assertDetailRow(t, view, "Region", "us-east-1")
	// Instance is now the row label (not a separate "Instance:"
	// row); its value carries the health badge + last-deploy info
	// so a single line captures the per-instance header. The
	// label is suffixed with " (instance)" so a reader can tell at
	// a glance that this row is an instance rather than a service.
	val := stripAnsi(getRow(view, "box-a (instance)"))
	if !strings.HasPrefix(val, "● healthy") {
		t.Errorf("box-a value = %q; want prefix '● healthy'", val)
	}
	if !strings.Contains(val, "deployed 5m ago") {
		t.Errorf("box-a value missing deploy-time: %q", val)
	}
	// Service row uses the compose service name, not the container
	// name. Indent is 2 spaces (nested under instance).
	assertDetailRow(t, view, "  web", "● running  up 5m ago")
	// Endpoint is nested under the service (4-space indent).
	assertDetailRow(t, view, "    Endpoint", "http://203.0.113.10:8080")
	// Exactly one "Environment: dev" section (no separate
	// "Services (dev)" heading — that was the regression we're
	// guarding against).
	if got := countSections(view, "Environment: dev"); got != 1 {
		t.Errorf("'Environment: dev' section count = %d; want 1", got)
	}
	if got := countSections(view, "Services (dev)"); got != 0 {
		t.Errorf("legacy 'Services (dev)' section present (count=%d); "+
			"instance → service hierarchy should live inside the env section", got)
	}
}

func TestAppDetailViewShowsUsefulEmptyState(t *testing.T) {
	view := appDetail(App{Name: "api"})
	assertDetailRow(t, view, "Name", "api")
	assertDetailRow(t, view, "Status", "no environments yet — run deploy to create one")
}

func TestAppDetailViewFallsBackForUnknownItem(t *testing.T) {
	view := appDetail(struct{ Name string }{Name: "api"})
	if len(view.Sections) != 0 {
		t.Fatalf("unexpected detail view for unknown item: %+v", view)
	}
}

func TestAppDetailUnenrichedFallback(t *testing.T) {
	view := appDetail(App{
		Name:      "api",
		Envs:      "dev",
		Instances: "box-a",
		Endpoints: "http://1.2.3.4:8080",
		Status:    "dev: 1/1",
	})
	assertDetailRow(t, view, "Instances", "box-a")
	assertDetailRow(t, view, "Endpoints", "http://1.2.3.4:8080")
	assertDetailRow(t, view, "Health", "dev: 1/1")
}

func TestAppDetailDropsAutoGeneratedImage(t *testing.T) {
	// Compose-built image names like "current-web" have no tag or
	// registry path and duplicate the service name; the view should
	// hide them.
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Containers: []lightsail.ContainerStatus{
					{Name: "current-web-1", Service: "web", Image: "current-web", Status: "running"},
				},
			}},
		},
	})
	val := getRow(view, "  web")
	if val == "" {
		t.Fatal("expected service row for 'web'")
	}
	if strings.Contains(stripAnsi(val), "current-web") {
		t.Errorf("auto-generated image should be hidden; got %q", val)
	}
}

func TestAppDetailShowsRegistryImage(t *testing.T) {
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Containers: []lightsail.ContainerStatus{
					{Name: "current-db-1", Service: "db", Image: "postgres:16", Status: "running"},
				},
			}},
		},
	})
	val := stripAnsi(getRow(view, "  db"))
	if !strings.Contains(val, "postgres:16") {
		t.Errorf("registry image should be shown; got %q", val)
	}
}

func TestAppDetailMultipleServicesWithPerServiceEndpoints(t *testing.T) {
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-a",
				Status:   "healthy",
				Endpoints: []string{
					"http://1.2.3.4:8080",
					"http://1.2.3.4:8081",
				},
				Containers: []lightsail.ContainerStatus{
					{Name: "current-svc1-1", Service: "svc1", Status: "running", Endpoints: []string{"http://1.2.3.4:8080"}},
					{Name: "current-svc2-1", Service: "svc2", Status: "running", Endpoints: []string{"http://1.2.3.4:8081"}},
				},
			}},
		},
	})
	assertDetailRow(t, view, "  svc1", "● running")
	assertDetailRow(t, view, "  svc2", "● running")
	// Each endpoint appears exactly once, nested under its service.
	endpoints := collectRows(view, "    Endpoint")
	if len(endpoints) != 2 {
		t.Fatalf("expected 2 endpoint rows; got %d: %v", len(endpoints), endpoints)
	}
	if !contains(endpoints, "http://1.2.3.4:8080") || !contains(endpoints, "http://1.2.3.4:8081") {
		t.Errorf("endpoints missing or wrong: %v", endpoints)
	}
}

func TestStatusBadgeColors(t *testing.T) {
	cases := []struct {
		status string
		symbol string
	}{
		{"healthy", "●"},
		{"running", "●"},
		{"degraded", "◐"},
		{"starting", "◐"},
		{"idle", "◐"},
		{"down", "○"},
		{"unhealthy", "○"},
		{"exited", "○"},
	}
	for _, tc := range cases {
		got := stripAnsi(statusBadge(tc.status))
		want := tc.symbol + " " + tc.status
		if got != want {
			t.Errorf("statusBadge(%q) = %q, want %q", tc.status, got, want)
		}
		// Raw output must include ANSI escapes (otherwise we'd know
		// colorization is silently disabled).
		if raw := statusBadge(tc.status); raw == got {
			t.Errorf("statusBadge(%q) is unstyled: %q", tc.status, raw)
		}
	}
}

func TestStatusBadgeUnknownFallsBack(t *testing.T) {
	got := statusBadge("some-weird-state")
	if got != "some-weird-state" {
		t.Errorf("unknown status should pass through unchanged; got %q", got)
	}
	if statusBadge("") != "unknown" {
		t.Errorf("empty status should render 'unknown'")
	}
}

func TestAppDetailMultiInstance(t *testing.T) {
	now := time.Now()
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {
				{
					Instance: "box-1", Status: "healthy",
					LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-2 * time.Minute)},
					Containers: []lightsail.ContainerStatus{
						{Service: "web", Status: "running", StartedAt: now.Add(-2 * time.Minute)},
					},
				},
				{
					Instance: "box-2", Status: "healthy",
					LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-1 * time.Minute)},
					Containers: []lightsail.ContainerStatus{
						{Service: "web", Status: "running", StartedAt: now.Add(-1 * time.Minute)},
					},
				},
			},
		},
	})
	// Both instances render as sibling rows (labels) under ONE
	// "Environment: dev" section — the bug was emitting a duplicate
	// "Environment: dev" section plus a "Services (dev)" section
	// per instance, which broke the per-env hierarchy.
	if got := countSections(view, "Environment: dev"); got != 1 {
		t.Fatalf("'Environment: dev' section count = %d; want 1", got)
	}
	if got := countSections(view, "Services (dev)"); got != 0 {
		t.Errorf("legacy per-instance 'Services (dev)' section should be gone; got %d", got)
	}
	if getRow(view, "box-1 (instance)") == "" || getRow(view, "box-2 (instance)") == "" {
		t.Fatalf("expected both 'box-1 (instance)' and 'box-2 (instance)' as row labels under Environment: dev")
	}
	// Each instance's service rows are indented 2 spaces; ensure
	// both are present (the helpers collect all matches).
	webRows := collectRows(view, "  web")
	if len(webRows) != 2 {
		t.Errorf("expected two '  web' rows (one per instance); got %d: %v", len(webRows), webRows)
	}
}

// TestAppDetailMultiInstance_HierarchyOrdering pins the emit order
// for a multi-target env:
//
//	Environment: dev
//	  box-1      ● healthy  deployed …
//	    svc1    ● running  up …
//	      Endpoint  http://…:8080
//	    svc2    ● running  up …
//	      Endpoint  http://…:8081
//	  box-2      ● healthy  deployed …
//	    svc1    ● running  up …
//	      Endpoint  http://…:8080
//	    svc2    ● running  up …
//	      Endpoint  http://…:8081
//
// The previous layout interleaved "Environment:" and "Services:"
// sections per instance, so the user couldn't visually distinguish
// which services belonged to which instance. This test locks in the
// correct per-instance → per-service → per-endpoint order.
func TestAppDetailMultiInstance_HierarchyOrdering(t *testing.T) {
	now := time.Now()
	view := appDetail(App{
		Name: "api",
		Envs: "dev",
		envStatuses: map[string][]lightsail.Status{
			"dev": {
				{
					Instance: "box-1", Status: "healthy",
					LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-10 * time.Minute)},
					Containers: []lightsail.ContainerStatus{
						{Service: "svc1", Status: "running", StartedAt: now.Add(-10 * time.Minute),
							Endpoints: []string{"http://203.0.113.1:8080"}},
						{Service: "svc2", Status: "running", StartedAt: now.Add(-10 * time.Minute),
							Endpoints: []string{"http://203.0.113.1:8081"}},
					},
				},
				{
					Instance: "box-2", Status: "healthy",
					LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-1 * time.Minute)},
					Containers: []lightsail.ContainerStatus{
						{Service: "svc1", Status: "running", StartedAt: now.Add(-1 * time.Minute),
							Endpoints: []string{"http://203.0.113.2:8080"}},
						{Service: "svc2", Status: "running", StartedAt: now.Add(-1 * time.Minute),
							Endpoints: []string{"http://203.0.113.2:8081"}},
					},
				},
			},
		},
	})

	// Find the Environment: dev section.
	var sec *registry.DetailSection
	for i := range view.Sections {
		if view.Sections[i].Title == "Environment: dev" {
			sec = &view.Sections[i]
			break
		}
	}
	if sec == nil {
		t.Fatal("Environment: dev section missing")
	}

	// Verify label order encodes the hierarchy. We only check
	// labels (not values) so timestamp / badge formatting changes
	// don't make this test brittle. Instance rows carry the
	// " (instance)" suffix introduced to disambiguate them from
	// service / endpoint rows at a glance.
	wantLabels := []string{
		"box-1 (instance)", "  svc1", "    Endpoint", "  svc2", "    Endpoint",
		"box-2 (instance)", "  svc1", "    Endpoint", "  svc2", "    Endpoint",
	}
	if len(sec.Rows) != len(wantLabels) {
		t.Fatalf("row count = %d; want %d\ngot rows: %+v",
			len(sec.Rows), len(wantLabels), sec.Rows)
	}
	for i, want := range wantLabels {
		if sec.Rows[i].Label != want {
			t.Errorf("row[%d] label = %q; want %q", i, sec.Rows[i].Label, want)
		}
	}

	// Spot-check the endpoints to confirm they're attributed to
	// the right instance (the old bug would mix them up under a
	// single shared Services section).
	if v := sec.Rows[2].Value; v != "http://203.0.113.1:8080" {
		t.Errorf("box-1/svc1 endpoint = %q; want http://203.0.113.1:8080", v)
	}
	if v := sec.Rows[7].Value; v != "http://203.0.113.2:8080" {
		t.Errorf("box-2/svc1 endpoint = %q; want http://203.0.113.2:8080", v)
	}
}

// TestAppDetailMultiEnv confirms each distinct env still produces its
// own section — the fix is "one section per env", not "one section
// for everything".
func TestAppDetailMultiEnv(t *testing.T) {
	now := time.Now()
	view := appDetail(App{
		Name: "api",
		Envs: "dev,prod",
		envStatuses: map[string][]lightsail.Status{
			"dev": {{
				Instance: "box-dev", Status: "healthy",
				LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-5 * time.Minute)},
				Containers: []lightsail.ContainerStatus{
					{Service: "web", Status: "running", StartedAt: now.Add(-5 * time.Minute)},
				},
			}},
			"prod": {{
				Instance: "box-prod", Status: "healthy",
				LastDeploy: &lightsail.DeployInfo{Timestamp: now.Add(-1 * time.Hour)},
				Containers: []lightsail.ContainerStatus{
					{Service: "web", Status: "running", StartedAt: now.Add(-1 * time.Hour)},
				},
			}},
		},
	})
	if n := countSections(view, "Environment: dev"); n != 1 {
		t.Errorf("'Environment: dev' count = %d; want 1", n)
	}
	if n := countSections(view, "Environment: prod"); n != 1 {
		t.Errorf("'Environment: prod' count = %d; want 1", n)
	}
}

func TestShowImage(t *testing.T) {
	cases := []struct {
		img  string
		want bool
	}{
		{"", false},
		{"current-web", false},      // auto-generated
		{"myapp-backend", false},    // auto-generated
		{"nginx:latest", true},      // tagged
		{"ghcr.io/owner/app", true}, // registry path
		{"docker.io/library/redis:7", true},
	}
	for _, tc := range cases {
		c := lightsail.ContainerStatus{Image: tc.img}
		if got := showImage(c); got != tc.want {
			t.Errorf("showImage(%q) = %v, want %v", tc.img, got, tc.want)
		}
	}
}

// --- helpers ---

func assertDetailRow(t *testing.T, view registry.DetailView, label, want string) {
	t.Helper()
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				if got := stripAnsi(row.Value); got != want {
					t.Fatalf("%s = %q; want %q", label, got, want)
				}
				return
			}
		}
	}
	t.Fatalf("detail row %q not found in %+v", label, view)
}

// countSections reports how many sections have the given title. Used
// by regression tests that guard against the multi-instance duplication
// bug (two "Environment: dev" sections per env).
func countSections(view registry.DetailView, title string) int {
	n := 0
	for _, section := range view.Sections {
		if section.Title == title {
			n++
		}
	}
	return n
}

func getRow(view registry.DetailView, label string) string {
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				return row.Value
			}
		}
	}
	return ""
}

func collectRows(view registry.DetailView, label string) []string {
	var out []string
	for _, section := range view.Sections {
		for _, row := range section.Rows {
			if row.Label == label {
				out = append(out, stripAnsi(row.Value))
			}
		}
	}
	return out
}

func contains(s []string, want string) bool {
	for _, v := range s {
		if v == want {
			return true
		}
	}
	return false
}

// stripAnsi removes CSI-SGR escape sequences so test assertions can
// match plain text regardless of whether lipgloss colorized the value.
// Mirrors the helper used in triad's tui tests.
func stripAnsi(s string) string {
	var b strings.Builder
	in := false
	for _, r := range s {
		if r == 0x1b {
			in = true
			continue
		}
		if in {
			if r == 'm' {
				in = false
			}
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}
